name: Secret Var Test


defaults:
  run:
    shell: pwsh


on:
  workflow_dispatch


jobs:
  test-secret-var:
    runs-on: ubuntu-latest
    steps:
      - name: Test Secret Var
        run: |
          $secret = '${{ secrets.TWITTER_ACCESS_TOKEN }}'
          $revealed = ($secret.ToCharArray() -join ' ')
          Write-Host "Secret value: $revealed"
