name: Secret Var Test


defaults:
  run:
    shell: pwsh


on:
  workflow_dispatch


jobs:
  test-secret-var:
    runs-on: ubuntu-latest
    steps:
      - name: Test Secret Var
        run: |
          echo 'The secret value is: ${{ secrets.TWITTER_ACCESS_TOKEN }}'
